### ISSUE TITLE
aclgen --shade_check "AttributeError: 'Term' object has no attribute 'sport'"

### ISSUE THREAD

**Issue by zombah** [google/capirca#163]
I have following traceback if i enable --shade-check for my policies:  
```
Traceback (most recent call last):
  File "/usr/bin/aclgen", line 11, in <module>
    load_entry_point('capirca==1.121', 'console_scripts', 'aclgen')()
  File "/usr/lib/python2.7/site-packages/capirca/aclgen.py", line 517, in entry_point
    app.run(main)
  File "/usr/lib/python2.7/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/usr/lib/python2.7/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/usr/lib/python2.7/site-packages/capirca/aclgen.py", line 501, in main
    result.get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'Term' object has no attribute 'sport'
```
I expect that maybe one of my policies causing this, but i can't figure where to put print to find which one or maybe there is known error which causing this?

**Comment by ankenyr** [comment]
I am unable to replicate this. Can you try and provide me with a pol file and relevant .net .svc files to replicate this? You may also wish to run aclgen with --policy_file path/to/pol_file.pol to get a better stack trace not obfuscated by pool.py

**Comment by zombah** [comment]
Hello @ankenyr,
Here is changes i added to sample_juniper_loopback.pol:
```
--- ../capirca/policies/pol/sample_juniper_loopback.pol 2018-08-09 01:44:24.344654915 +0300
+++ ./policies/tests/pol/sample_juniper_loopback.pol    2018-10-06 14:31:42.284842373 +0300
@@ -40,6 +40,16 @@
   action:: accept
 }
 
+term accept-bgp-port {
+  comment:: "Allow BGP port requests."
+  source-prefix:: configured-neighbors-only
+  destination-prefix:: configured-neighbors-only
+  port:: BGP
+  protocol:: tcp
+  counter:: bgp-port
+  action:: accept
+}
+
 term accept-ospf {
   comment:: "Allow outbound OSPF traffic from other RFC1918 routers."
   source-address:: INTERNAL
```

here is trace output with --policy_file:
```
I1006 14:31:52.700145 140071386130176 aclgen.py:477] rendering one file
Traceback (most recent call last):
  File "/usr/local/bin/aclgen", line 9, in <module>
    load_entry_point('capirca==1.121', 'console_scripts', 'aclgen')()
  File "/usr/local/lib/python2.7/dist-packages/capirca/aclgen.py", line 517, in entry_point
    app.run(main)
  File "/home/zombah/.local/lib/python2.7/site-packages/absl/app.py", line 278, in run
    _run_main(main, args)
  File "/home/zombah/.local/lib/python2.7/site-packages/absl/app.py", line 239, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/capirca/aclgen.py", line 479, in main
    FLAGS.exp_info, write_files)
  File "/usr/local/lib/python2.7/dist-packages/capirca/aclgen.py", line 186, in RenderFile
    base_dir=FLAGS.base_directory, shade_check=FLAGS.shade_check)
  File "/usr/local/lib/python2.7/dist-packages/capirca/lib/policy.py", line 2473, in ParsePolicy
    policy = p.parse(preprocessed_data, lexer=lexer)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/lib/python2.7/dist-packages/capirca/lib/policy.py", line 1840, in p_target
    p[0] = Policy(p[2], p[3])
  File "/usr/local/lib/python2.7/dist-packages/capirca/lib/policy.py", line 186, in __init__
    self.AddFilter(header, terms)
  File "/usr/local/lib/python2.7/dist-packages/capirca/lib/policy.py", line 193, in AddFilter
    self._DetectShading(terms)
  File "/usr/local/lib/python2.7/dist-packages/capirca/lib/policy.py", line 270, in _DetectShading
    if (term in terms[prior_index]
  File "/usr/local/lib/python2.7/dist-packages/capirca/lib/policy.py", line 551, in __contains__
    self.CheckPortIsContained(self.port, other.sport) or
AttributeError: 'Term' object has no attribute 'sport'
```

**Comment by ankenyr** [comment]
This should be fixed in the latest export of changes.
