### ISSUE TITLE
aclgen execute got ImportError: 'module' object has no attribute 'entry_point'

### ISSUE THREAD

**Issue by lyricjixh** [google/capirca#199]
following the instruction completed the dependency (requirement.txt) intallation, setup.py build and install.

But the aclgen execution always gives the following errors...

$ aclgen --help
Traceback (most recent call last):
  File "/usr/local/bin/aclgen", line 9, in <module>
    load_entry_point('capirca==1.122', 'console_scripts', 'aclgen')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'entry_point'

**Comment by lyricjixh** [comment]
never mind, just #194
