### ISSUE TITLE
multiprocessing.get_context() not valid python2.7 attribute

### ISSUE THREAD

**Issue by lyricjixh** [google/capirca#200]
$ python aclgen.py
Traceback (most recent call last):
  File "aclgen.py", line 543, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "aclgen.py", line 534, in main
    self.context = multiprocessing.get_context()
AttributeError: 'module' object has no attribute 'get_context'

**Comment by taliamax** [comment]
I think python2 support is officially dropped on this project https://github.com/google/capirca/issues/172

**Comment by lyricjixh** [comment]
thanks for the confirmation.
