### ISSUE TITLE
Tests failing after last couple of commits, need to work on export process

### ISSUE THREAD

**Issue by ankenyr** [google/capirca#64]
I am aware that a couple of tests are failing currently. I will fix these soon unless someone else gets to them first. These seem to have been introduced in part due to our process in exporting changes. I need to investigate what went wrong and how we can fix this so it does not happen again.

======================================================================
ERROR: testHopLimit (capirca.tests.juniper_test.JuniperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/robankeny/Desktop/capirca/tests/juniper_test.py", line 508, in testHopLimit
    self.naming), EXP_INFO)
  File "/usr/local/lib/python2.7/dist-packages/capirca-1.109-py2.7.egg/lib/policy.py", line 2158, in ParsePolicy
    return p.parse(preprocessed_data, lexer=lexer)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/capirca-1.109-py2.7.egg/lib/policy.py", line 2035, in p_error
    % (p.value, p.type, p.lineno, use_token))
ParseError:  ERROR on "hop-limit" (type STRING, line 7, Next ':')

======================================================================
ERROR: testHopLimitRange (capirca.tests.policy_test.PolicyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/robankeny/Desktop/capirca/tests/policy_test.py", line 538, in testHopLimitRange
    ret = policy.ParsePolicy(pol, self.naming)
  File "/usr/local/lib/python2.7/dist-packages/capirca-1.109-py2.7.egg/lib/policy.py", line 2158, in ParsePolicy
    return p.parse(preprocessed_data, lexer=lexer)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/capirca-1.109-py2.7.egg/lib/policy.py", line 2035, in p_error
    % (p.value, p.type, p.lineno, use_token))
ParseError:  ERROR on "hop-limit" (type STRING, line 9, Next ':')

======================================================================
ERROR: testHopLimitSingle (capirca.tests.policy_test.PolicyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/robankeny/Desktop/capirca/tests/policy_test.py", line 531, in testHopLimitSingle
    ret = policy.ParsePolicy(pol, self.naming)
  File "/usr/local/lib/python2.7/dist-packages/capirca-1.109-py2.7.egg/lib/policy.py", line 2158, in ParsePolicy
    return p.parse(preprocessed_data, lexer=lexer)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/capirca-1.109-py2.7.egg/lib/policy.py", line 2035, in p_error
    % (p.value, p.type, p.lineno, use_token))
ParseError:  ERROR on "hop-limit" (type STRING, line 9, Next ':')

======================================================================
ERROR: testTermNameConflict (capirca.tests.packetfilter_test.PacketFilterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/robankeny/Desktop/capirca/tests/packetfilter_test.py", line 701, in testTermNameConflict
    packetfilter.DuplicateTermError,
AttributeError: 'module' object has no attribute 'DuplicateTermError'

----------------------------------------------------------------------
Ran 436 tests in 29.282s

**Comment by ankenyr** [comment]
Ok tests are passing again with the last commit. Waiting for the next external commit to test how we pull in changes. I feel we can close this as the problem is an internal problem.
