### ISSUE TITLE
Missing dependencies ipaddr and gflags

### ISSUE THREAD

**Issue by jzohrab** [google/capirca#65]
I believe there's a broken dependency introduced as at "Sync internal and external repositories":

```
commit d450b92ce4efc3943a8176f56ad767c90670ea0a
... snip ...
    Sync internal and external repositories.
... snip ...
+import ipaddr
-from third_party import ipaddr
```

ipaddr isn't included in requirements.txt.

Running a test, eg, gives the following:

```
(venv) ~/Documents/Projects/capirca$ python -m tests.naming_test
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/jzohrab/Documents/Projects/capirca/tests/naming_test.py", line 22, in <module>
    from lib import nacaddr
  File "lib/nacaddr.py", line 20, in <module>
    import ipaddr
ImportError: No module named ipaddr
```

**Comment by jzohrab** [comment]
Changed title.  Working locally on my merge of google/master to my development branch.  Added ipaddr to requirements and got past that error, found another:

```
ERROR: test.integration.test_aclgen (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.integration.test_aclgen
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/jzohrab/Documents/Projects/capirca/test/integration/test_aclgen.py", line 24, in <module>
    import aclgen
  File "/Users/jzohrab/Documents/Projects/capirca/aclgen.py", line 53, in <module>
    import gflags as flags
ImportError: No module named gflags
```

FYI.  I'll continue to work through my issues on my dev branch, I'm building from a clean environment.

**Comment by jzohrab** [comment]
FYI 2: I'm pushing my work to https://github.com/jzohrab/capirca/commits/merge_master

Currently tests are failing in a few places, and some errors happening with the new code that shouldn't (e.g., "/capirca/aclgen.py:441: RuntimeWarning: Trying to access flag optimize before flags were parsed. This will raise an exception in the future.").  Will commit separately in that merge branch as I work through issues.

**Comment by jzohrab** [comment]
alas, this is a dup of https://github.com/google/capirca/pull/60.  Leaving this open for google team and @ankenyr to be aware I'm working on the merge as well, close it if you'd like.

**Comment by ankenyr** [comment]
Guessing you install this with pip then? I have only tested it with setup.py which should have this as a dependency.
https://github.com/google/capirca/blob/master/setup.py#L49
I will ping the pull request as there are still outstanding actions needed to be taken.

**Comment by jzohrab** [comment]
Yes, I was using requirements.txt.  I'm using virtualenv if it makes any difference.  Not a huge deal, I'll deal with it and we can discuss in near future, as this is already in #60.  Thanks @ankenyr.
